
import javax.swing.DefaultListModel;


/**
 *
 * @author umair
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        readyList.setModel(ready);
        runningList.setModel(waiting);
        waitingList.setModel(running);
        
        int io =0;
        int execTime=5; //5 seconds default
        
        ThreadDemo T1 = new ThreadDemo( "Thread-1");
        T1.start();
        ThreadDemo T2= new ThreadDemo("Thread-2");
        T2.start();
        ThreadDemo T3= new ThreadDemo ("Thread-3");
        T3.start();
        ThreadDemo T4= new ThreadDemo ("Thread-4");
        T4.start();
        ThreadDemo T5= new ThreadDemo ("Thread-5");
        T5.start();
        ThreadDemo T6= new ThreadDemo ("Thread-6");
        T6.start();
    }
    
   public class ThreadDemo extends Thread {
   private Thread t;
   private String threadName;
   
   
   ThreadDemo( String name){
       threadName = name;
       System.out.println("Creating " +  threadName );
       jTextArea1.append("Creating " +  threadName + "\n");
       ready.addElement(name);
       
       
       
   }
   public void run() {
      System.out.println("Running " +  threadName );
      jTextArea1.append("Running " +  threadName + "\n");
      ready.removeElement(threadName);
      running.addElement(threadName);
      try {
         for(int i = 4; i > 0; i--) {
            jTextArea1.append("Thread: " + threadName + ", " + i + "\n");
            System.out.println("Thread: " + threadName + ", " + i );
            // Let the thread sleep for a while.
            Thread.sleep(2000);
         }
     } catch (InterruptedException e) {
         System.out.println("Thread " +  threadName + " interrupted.");
         jTextArea1.append("Thread " +  threadName + " interrupted."+ "\n");
     }
     System.out.println("Thread " +  threadName + " exiting.");
     jTextArea1.append("Thread " +  threadName + " exiting."+ "\n");
     running.removeElement(threadName);
   }
   
   public void start ()
   {
      
      System.out.println("Starting " +  threadName );
      jTextArea1.append("Thread " +  threadName + " exiting."+ "\n");
      if (t == null)
      {
         t = new Thread (this, threadName);
          waiting.addElement(threadName);
         t.start ();
      }
   }

}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        readyList = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        waitingList = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        runningList = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Process Scheduler");
        getContentPane().add(jLabel2);
        getContentPane().add(jSeparator1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 3, 5, 0));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ready Queue");
        jPanel2.add(jLabel3);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Running");
        jPanel2.add(jLabel4);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Waiting");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2);

        jPanel1.setLayout(new java.awt.GridLayout(1, 3, 5, 0));

        jScrollPane2.setViewportView(readyList);

        jPanel1.add(jScrollPane2);

        jScrollPane3.setViewportView(waitingList);

        jPanel1.add(jScrollPane3);

        jScrollPane1.setViewportView(runningList);

        jPanel1.add(jScrollPane1);

        getContentPane().add(jPanel1);

        jPanel3.setPreferredSize(new java.awt.Dimension(100, 400));
        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel3.add(jSeparator2, java.awt.BorderLayout.CENTER);

        jLabel5.setText("Statistics:");
        jPanel3.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setPreferredSize(new java.awt.Dimension(164, 500));
        jScrollPane4.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }
    DefaultListModel ready =new DefaultListModel();
    DefaultListModel waiting =new DefaultListModel();
    DefaultListModel running =new DefaultListModel();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JList readyList;
    private javax.swing.JList runningList;
    private javax.swing.JList waitingList;
    // End of variables declaration//GEN-END:variables
}
